// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v5.26.1
// source: demo/demo.proto

package demo

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	Demo_ClientStream_FullMethodName = "/Demo/ClientStream"
)

// DemoClient is the client API for Demo service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DemoClient interface {
	ClientStream(ctx context.Context, opts ...grpc.CallOption) (Demo_ClientStreamClient, error)
}

type demoClient struct {
	cc grpc.ClientConnInterface
}

func NewDemoClient(cc grpc.ClientConnInterface) DemoClient {
	return &demoClient{cc}
}

func (c *demoClient) ClientStream(ctx context.Context, opts ...grpc.CallOption) (Demo_ClientStreamClient, error) {
	stream, err := c.cc.NewStream(ctx, &Demo_ServiceDesc.Streams[0], Demo_ClientStream_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &demoClientStreamClient{stream}
	return x, nil
}

type Demo_ClientStreamClient interface {
	Send(*Ping) error
	CloseAndRecv() (*Pong, error)
	grpc.ClientStream
}

type demoClientStreamClient struct {
	grpc.ClientStream
}

func (x *demoClientStreamClient) Send(m *Ping) error {
	return x.ClientStream.SendMsg(m)
}

func (x *demoClientStreamClient) CloseAndRecv() (*Pong, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(Pong)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// DemoServer is the server API for Demo service.
// All implementations should embed UnimplementedDemoServer
// for forward compatibility
type DemoServer interface {
	ClientStream(Demo_ClientStreamServer) error
}

// UnimplementedDemoServer should be embedded to have forward compatible implementations.
type UnimplementedDemoServer struct {
}

func (UnimplementedDemoServer) ClientStream(Demo_ClientStreamServer) error {
	return status.Errorf(codes.Unimplemented, "method ClientStream not implemented")
}

// UnsafeDemoServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DemoServer will
// result in compilation errors.
type UnsafeDemoServer interface {
	mustEmbedUnimplementedDemoServer()
}

func RegisterDemoServer(s grpc.ServiceRegistrar, srv DemoServer) {
	s.RegisterService(&Demo_ServiceDesc, srv)
}

func _Demo_ClientStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(DemoServer).ClientStream(&demoClientStreamServer{stream})
}

type Demo_ClientStreamServer interface {
	SendAndClose(*Pong) error
	Recv() (*Ping, error)
	grpc.ServerStream
}

type demoClientStreamServer struct {
	grpc.ServerStream
}

func (x *demoClientStreamServer) SendAndClose(m *Pong) error {
	return x.ServerStream.SendMsg(m)
}

func (x *demoClientStreamServer) Recv() (*Ping, error) {
	m := new(Ping)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// Demo_ServiceDesc is the grpc.ServiceDesc for Demo service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Demo_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "Demo",
	HandlerType: (*DemoServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ClientStream",
			Handler:       _Demo_ClientStream_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "demo/demo.proto",
}
